### PR TITLE
Fix https://github.com/tmux-plugins/tmux-resurrect/issues/176.

### LINKED ISSUE #176: save with zoomed window leads to flickering
Wenn I zoomed into a pane and trigger save it zooms out and back in again. This is annoying if you use tmux-continuum, too, because the pane flickers every couple of minutes.

### PR DESCRIPTION
**Pull request by woutgg**
This removes (un)zooming on save which should not be necessary anymore with recent tmux versions, this should fix #176.
I think the relevant change in tmux itself has been made in [this commit](https://github.com/tmux/tmux/commit/531869bd92f0daff3cc3c3cc0ab273846f411dc8), so this change should work for tmux >=2.2.

Update: I have extended the tests a bit to also save and restore a zoomed pane.

### CODE REVIEW

File: scripts/save.sh [hunk 1]
```diff
@@ -246,14 +246,8 @@ dump_windows() {
 			fi
 			# window_layout is not correct for zoomed windows
 			if [[ "$window_flags" == *Z* ]]; then
```
Comment (bruno-) [inline scripts/save.sh]: Can't we just remove this whole `if` block? I can't see what value does a line that reassigns `window_layout` provides?

**Comment by bruno-** [comment]
Tested and this works ok. Will merge after PR feedback is addressed (or clarified). Thanks for the PR

**Comment by woutgg** [comment]
You are right, I was a bit too quick with the initial fix.
